/* Real browser acceptance against a running local four-process lab. */
const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
(async () => {
  const directory = process.argv[2];
  const analyst = JSON.parse(fs.readFileSync(path.join(directory, 'analyst.json')));
  const decoy = JSON.parse(fs.readFileSync(path.join(directory, 'decoy.json')));
  const browser = await chromium.launch({headless: true, args:['--no-sandbox']});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  try {
    const base = 'http://127.0.0.1:'+analyst.port;
    await page.goto(base);
    await page.locator('#login').waitFor({state:'visible'});
    await page.fill('#password',analyst.password);
    await page.click('#login-form button');
    await page.locator('#workspace').waitFor({state:'visible'});
    await page.waitForFunction(()=>document.querySelectorAll('#fleet-cards .vehicle').length===3);
    await page.click('#control button');
    await page.waitForFunction(()=>document.querySelector('#control-result').textContent.includes('Accepted'));
    await page.waitForFunction(()=>Number(document.querySelector('.speed').textContent.replace('km/h',''))>0);
    const fleet = await context.newPage();
    await fleet.goto('http://127.0.0.1:'+decoy.port);
    await fleet.click('#document');
    await fleet.locator('#document-result').waitFor({state:'visible'});
    const document = JSON.parse(await fleet.locator('#document-result').textContent());
    assert(document.credentials.username.startsWith('test-lab:'));
    await page.waitForFunction(()=>Number(document.getElementById('events-count').textContent)>110,null,{timeout:20000});
    await page.click('[data-tab="evidence"]');
    await page.waitForFunction(()=>document.querySelectorAll('#sessions .session-row').length>0);
    await page.click('[data-tab="overview"]');
    fs.mkdirSync('docs/images',{recursive:true});
    await page.screenshot({path:'docs/images/analyst-overview.png',fullPage:true});
    await page.click('[data-tab="replay"]');
    const downloadPromise=page.waitForEvent('download');
    await page.click('#export');
    const download=await downloadPromise;
    const exported=path.join(directory,'browser-scenario.json');
    await download.saveAs(exported);
    await page.setInputFiles('#replay-file',exported);
    await page.waitForFunction(()=>document.querySelector('#replay-result').textContent.includes('"verified": true'));
    await page.click('[data-tab="overview"]');
    const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true});
    await mobile.addCookies(await context.cookies());
    const mobilePage=await mobile.newPage();
    mobilePage.on('pageerror',error=>errors.push(error.message));
    await mobilePage.goto(base);
    await mobilePage.locator('#workspace').waitFor({state:'visible'});
    await mobilePage.waitForFunction(()=>document.querySelectorAll('#fleet-cards .vehicle').length===3);
    assert.equal(await mobilePage.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
    await mobilePage.screenshot({path:'docs/images/analyst-mobile.png',fullPage:true});
    await page.click('#logout');
    await page.locator('#login').waitFor({state:'visible'});
    assert.equal((await page.request.get(base+'/api/state')).status(),401);
    assert.deepEqual(errors,[]);
    console.log(JSON.stringify({desktop:true,mobile:true,control:true,export_replay:true,logout:true,page_errors:errors}));
    await mobile.close();
  } finally {await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
