'use strict';
const $=id=>document.getElementById(id);let csrf='',stream=null,cursor=0,events=[],histories=new Map(),busy=false,state=null,graphBusy=false;
const svgNS='http://www.w3.org/2000/svg';
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function notice(text){$('notice').textContent=text;}
async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.method?{'X-CSRF-Token':csrf}:{}),...options.headers};const response=await fetch(path,{...options,headers});if(!response.ok){if(response.status===401){showLogin();}let error=await response.json().catch(()=>({error:'Request failed'}));throw new Error(error.error||'Request failed');}return response.json();}
function showLogin(){if(stream)stream.close();stream=null;csrf='';$('workspace').hidden=true;$('login').hidden=false;$('connection').textContent='Private workspace';}
async function enter(){const session=await api('/api/session');csrf=session.csrf;$('login').hidden=true;$('workspace').hidden=false;await refresh();connect();await refreshGraph();}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();try{const result=await api('/api/login',{method:'POST',body:JSON.stringify({password:$('password').value})});csrf=result.csrf;$('password').value='';$('login-error').textContent='';await enter();}catch(error){$('login-error').textContent=error.message;}});
function connect(){if(stream)stream.close();stream=new EventSource('/api/stream?after='+cursor);stream.onmessage=e=>{const event=JSON.parse(e.data);if(event.sequence<=cursor)return;cursor=event.sequence;events.push(event);if(events.length>500)events.shift();if(event.event_type==='canary.used'||event.event_type==='artifact.read')refreshGraph().catch(error=>notice(error.message));renderEvents();};stream.onerror=()=>{if(!state)$('connection').textContent='Connecting';};}
function renderEvents(){const body=$('timeline');body.replaceChildren();for(const event of events.filter(e=>e.event_type!=='state.updated').slice(-100).reverse()){const row=node('tr');for(const value of ['#'+event.sequence,event.event_type,event.source_adapter,event.vehicle_id||event.session_id||'—',event.tick])row.append(node('td',String(value)));body.append(row);}$('events-count').textContent=String(cursor);$('event-latest').textContent=events.at(-1)?.event_type||'Awaiting evidence';}
function renderFleet(projection){const snapshot=projection.snapshot;state=snapshot;$('vehicles-count').textContent=String(snapshot.states.length);$('simulation-time').textContent=(snapshot.tick/10).toFixed(1)+' s';$('run-name').textContent=projection.run_id;$('version').textContent='State version '+snapshot.tick;$('connection').textContent=projection.stale?'Stale projection':snapshot.running?'Live · synchronized':'Run stopped';const selected=$('vehicle-select').value;if($('vehicle-select').options.length!==snapshot.states.length){$('vehicle-select').replaceChildren(...snapshot.states.map(s=>{const option=node('option',s.vehicle_id);option.value=s.vehicle_id;return option;}));if(selected)$('vehicle-select').value=selected;}
const cards=$('fleet-cards');cards.replaceChildren();for(const vehicle of snapshot.states){let history=histories.get(vehicle.vehicle_id)||[];if(!history.length||history.at(-1).tick!==snapshot.tick){history.push({tick:snapshot.tick,speed:vehicle.speed_mm_s});if(history.length>60)history.shift();histories.set(vehicle.vehicle_id,history);}const card=node('article',undefined,'vehicle'),top=node('div',undefined,'vehicle-top');top.append(node('span',vehicle.vehicle_id,'vehicle-id'),node('span',vehicle.ignition?'● Engine on':'○ Engine off','vehicle-status'));card.append(top);const speed=node('div',(vehicle.speed_mm_s*0.0036).toFixed(1),'speed');speed.append(node('small','km/h'));card.append(speed);const svg=document.createElementNS(svgNS,'svg');svg.setAttribute('viewBox','0 0 250 35');svg.classList.add('spark');const line=document.createElementNS(svgNS,'polyline');line.setAttribute('points',history.map((p,i)=>`${i*250/Math.max(1,history.length-1)},${33-p.speed/45000*30}`).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#7be7c4');line.setAttribute('stroke-width','1.5');svg.append(line);card.append(svg);const detail=node('div',undefined,'vehicle-details');detail.append(node('span','Fuel '+(vehicle.fuel_ml/1000).toFixed(1)+' L'),node('span','Throttle '+vehicle.throttle_permille/10+'%'),node('span','Brake '+vehicle.brake_permille/10+'%'));card.append(detail);cards.append(card);}renderMap(projection);}
function renderMap(projection){const group=$('map-points');group.replaceChildren();const route=projection.route||[];if(!route.length)return;const lats=route.map(p=>p.latitude_e7),lons=route.map(p=>p.longitude_e7),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons);const point=p=>[65+(p.longitude_e7-minLon)/Math.max(1,maxLon-minLon)*510,235-(p.latitude_e7-minLat)/Math.max(1,maxLat-minLat)*190];const line=document.createElementNS(svgNS,'polyline');line.setAttribute('points',route.map(p=>point(p).join(',')).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#385963');line.setAttribute('stroke-width','9');line.setAttribute('stroke-linejoin','round');group.append(line);for(const [i,vehicle] of projection.snapshot.states.entries()){const [x,y]=point(vehicle);const circle=document.createElementNS(svgNS,'circle');circle.setAttribute('cx',x);circle.setAttribute('cy',y);circle.setAttribute('r',7);circle.setAttribute('fill',['#7be7c4','#b8bcff','#ffc890'][i%3]);circle.setAttribute('stroke','#0b131a');circle.setAttribute('stroke-width','3');const title=document.createElementNS(svgNS,'title');title.textContent=vehicle.vehicle_id;circle.append(title);group.append(circle);const label=document.createElementNS(svgNS,'text');label.setAttribute('x',x+12);label.setAttribute('y',y-15-i*14);label.setAttribute('fill','#adc5d0');label.setAttribute('font-size','10');label.textContent=vehicle.vehicle_id;group.append(label);}$('map-coordinates').textContent='Local loop · version '+projection.snapshot.tick;}
async function refresh(){if(busy||!csrf)return;busy=true;try{renderFleet(await api('/api/state'));notice('');}catch(error){notice(error.message);}finally{busy=false;}}
async function refreshGraph(){if(graphBusy||!csrf)return;graphBusy=true;try{const result=await api('/api/graph');$('edges-count').textContent=String(new Set(result.edges.flatMap(e=>[e.source_session,e.target_session])).size);$('graph').replaceChildren();if(!result.edges.length)$('graph').append(node('div','No linked sessions yet. Open the portal maintenance document and use its synthetic MQTT credentials.','empty'));for(const edge of result.edges){const card=node('div',undefined,'link-card'),source=node('div',edge.source_session),target=node('div',edge.target_session),middle=node('div','→ Exact token reuse','edge');source.append(node('small','HTTP · '+edge.source_event_id));target.append(node('small','MQTT · '+edge.target_event_id));middle.append(node('small',edge.confidence+' confidence · artifact access'));card.append(source,middle,target);$('graph').append(card);}$('sessions').replaceChildren();for(const session of result.sessions){const row=node('div',undefined,'session-row');row.append(node('span',session.id),node('small',session.adapter+' · '+session.events+' observations'));$('sessions').append(row);}}finally{graphBusy=false;}}
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('active',b===button);for(const page of document.querySelectorAll('[data-page]'))page.hidden=page.dataset.page!==button.dataset.tab;$('crumb').textContent=button.textContent.replace(/^[^\w]+/,'').toUpperCase();window.scrollTo({top:0});if(button.dataset.tab==='evidence')refreshGraph().catch(error=>notice(error.message));});
$('control').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const vehicle_id=$('vehicle-select').value;let results=[];for(const [operation,value] of [['set_ignition',$('ignition').value==='true'],['set_throttle',Number($('throttle').value)],['set_brake',Number($('brake').value)]]){results.push(await api('/api/commands',{method:'POST',body:JSON.stringify({vehicle_id,command_id:'ui-'+crypto.randomUUID(),operation,value})}));}$('control-result').textContent=results.every(r=>r.status==='accepted')?'Accepted · scheduled for next tick':results.map(r=>r.reason_code).join(', ');await refresh();}catch(error){$('control-result').textContent=error.message;}finally{button.disabled=false;}});
$('refresh-graph').addEventListener('click',()=>refreshGraph().catch(error=>notice(error.message)));
$('stop').addEventListener('click',async()=>{try{await api('/api/stop',{method:'POST',body:'{}'});await refresh();}catch(error){notice(error.message);}});
$('logout').addEventListener('click',async()=>{try{await api('/api/logout',{method:'POST',body:'{}'});showLogin();}catch(error){notice(error.message);}});
$('export').addEventListener('click',async()=>{try{const bundle=await api('/api/export'),url=URL.createObjectURL(new Blob([JSON.stringify(bundle,null,2)+'\n'],{type:'application/json'}));const link=node('a');link.href=url;link.download='miragetransit-scenario.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(error){notice(error.message);}});
$('replay-file').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;if(file.size>16*1024*1024){$('replay-result').textContent='Scenario exceeds 16 MiB.';return;}try{$('replay-result').textContent='Verifying…';const result=await api('/api/replay',{method:'POST',body:await file.text()});$('replay-result').textContent=JSON.stringify(result,null,2);}catch(error){$('replay-result').textContent=error.message;}});
setInterval(refresh,1000);enter().catch(()=>showLogin());
